### ISSUE TITLE
SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by adocampo** [drtweety/busman#11]
Just stumbled upon this project and searching for inspiration I wanted to try it out. But I couldn't even start it.
`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty`

I've set up the SECRET_KEY on several places: 
 - busman/settings.py
 - env/lib/python3.9/site-packages/tests/settings.py
 - env/lib/python3.9/site-packages/crispy_forms/tests/test_settings.py
 - env/lib/python3.9/site-packages/django/conf/global_settings.py

but no luck, the message always appears.

Any idea?

**Comment by daniyaalk** [comment]
Very sorry for the late reply, you have to set the secret key as an environment variable.
`export SECRET_KEY=[SECRET_KEY_HERE]`
